import { BANKS, getBank } from '../../data/banks.js'
import { normalizeRecipientBank } from '../../data/recipientBanks.js'
import { formatMoney } from '../../utils/format.js'
import { APP_TIMEZONE, zonedParts } from '../../utils/time.js'
import { LOOKALIKE_THRESHOLD, recipientSimilarity } from '../features.js'
import { extractEntities } from './extract.js'
import { LANGUAGE_PATTERNS } from './patterns.js'

// Evidence comparison: checks what a pasted message or document says
// (entities from extract.js) against the pending standing-order request and
// the user's profile (profile.js).
//
// It reports evidence and never decides. There is no fraud probability, no
// score, no model and no change to the six rule-based checks. A later
// assessment layer decides what the evidence means.
//
// Pure and deterministic: the same inputs always give the same result.
//
// Every signal has one of five categories:
//   MATCH       — the text agrees with the request;
//   CONFLICT    — the text disagrees with the request;
//   SUSPICIOUS  — worth attention, but there is nothing on the request to
//                 compare it with (a sender claim, a request for a PIN, a
//                 look-alike link, contradictions within the text);
//   UNCOMPARED  — present in the text, neither suspicious nor comparable,
//                 because the request does not record that field;
//   NOT_PRESENT — the text says nothing about the field. This is recorded on
//                 `fields` only; it never produces a signal or a finding.
// Missing evidence is never treated as suspicious.

export const EVIDENCE_CATEGORIES = ['MATCH', 'CONFLICT', 'SUSPICIOUS', 'UNCOMPARED', 'NOT_PRESENT']

const DAY_MS = 24 * 60 * 60 * 1000

// fraud.auth's standing-order references ("SO-12345") are generated by the app,
// so a reference quoted in the text can never match them.
const INTERNAL_REFERENCE = /^SO-\d+$/i

// Domain words that dress a link up as a bank security page.
const SECURITY_DOMAIN_WORDS = new Set([
  'secure', 'security', 'verify', 'verification', 'login', 'signin', 'update', 'review', 'support',
  'protect', 'protection', 'account', 'accounts', 'banking', 'alert', 'safe', 'unlock', 'confirm',
])

// Bank names as they appear inside domain labels: "mcb", "sbm", "maubank".
const BANK_DOMAIN_TOKENS = new Map(
  BANKS.flatMap((bank) => [bank.code, bank.name].map((name) => [name.toLowerCase().replace(/[^a-z0-9]/g, ''), bank.code])),
)

const SENSITIVE_INFO = new RegExp(LANGUAGE_PATTERNS.find((pattern) => pattern.id === 'sensitiveInfo').pattern.source, 'gi')

// --- Helpers ----------------------------------------------------------------

const digitsOf = (value) => String(value ?? '').replace(/\D/g, '')
const unique = (values) => [...new Set(values)]
const cents = (value) => Math.round(value * 100)
const bankName = (code) => getBank(code)?.name ?? code
const quote = (text) => `“${text}”`
const list = (values) => values.map(quote).join(', ')
const normalizeReference = (value) => String(value).toUpperCase().replace(/[^A-Z0-9]/g, '')
const isoDay = ({ year, month, day }) => `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`
const dayNumber = ({ year, month, day }) => Date.UTC(year, month - 1, day) / DAY_MS

function money(value, currency) {
  const formatted = formatMoney(value)
  return !currency || currency === 'MUR' ? formatted : formatted.replace(/^Rs\s*/, `${currency} `)
}

function field(status, request, extracted, extra = {}) {
  return { status, request: request ?? null, extracted, ...extra }
}

const notPresent = (request) => field('NOT_PRESENT', request, [])

function signal(signals, id, fieldName, category, tone, text, evidence = []) {
  signals.push({ id, field: fieldName, category, tone, text, evidence })
}

// The field status from the categories of its signals: any conflict wins,
// then a match, then an uncompared value.
function statusOf(signals, fieldName) {
  const categories = new Set(signals.filter((s) => s.field === fieldName).map((s) => s.category))
  for (const category of ['CONFLICT', 'SUSPICIOUS', 'MATCH', 'UNCOMPARED']) if (categories.has(category)) return category
  return 'NOT_PRESENT'
}

// --- Comparisons ------------------------------------------------------------

function compareAmount(extracted, request, signals) {
  const amounts = extracted.amounts
  if (!amounts.length) return notPresent(request.amount)
  const values = amounts.map(({ value, currency }) => ({ value, currency }))
  if (request.amount == null) {
    signal(signals, 'amount.uncompared', 'amount', 'UNCOMPARED', null, 'The text states an amount, but the request has none to compare it with.', values)
    return field('UNCOMPARED', null, values)
  }

  const sameCurrency = (amount) => !request.currency || amount.currency === request.currency
  const matching = amounts.filter((amount) => sameCurrency(amount) && cents(amount.value) === cents(request.amount))
  const distinct = unique(amounts.map((amount) => `${amount.currency} ${cents(amount.value)}`))
  const requested = money(request.amount, request.currency)

  if (matching.length && distinct.length === 1) {
    signal(signals, 'amount.match', 'amount', 'MATCH', 'ok', `The text states ${requested}, the same amount as the request.`, values)
  } else if (matching.length) {
    signal(signals, 'amount.match', 'amount', 'MATCH', 'ok', `The text states ${requested}, the same amount as the request, alongside other amounts.`, values)
  } else {
    // One clearly stated amount that differs is strong evidence; several
    // amounts, none of them the requested one, are weaker.
    const stated = unique(amounts.map((amount) => money(amount.value, amount.currency))).join(', ')
    const clear = distinct.length === 1
    signal(
      signals,
      'amount.mismatch',
      'amount',
      'CONFLICT',
      clear ? 'bad' : 'warn',
      clear ? `The text states ${stated}, but the request is for ${requested}.` : `The text mentions ${stated}, none of them the requested ${requested}.`,
      values,
    )
  }
  return field(statusOf(signals, 'amount'), request.amount, values)
}

function compareCurrency(extracted, request, signals) {
  const codes = unique(extracted.currencies.map((currency) => currency.code))
  if (!codes.length) return notPresent(request.currency)
  if (!request.currency) {
    signal(signals, 'currency.uncompared', 'currency', 'UNCOMPARED', null, `The text uses ${codes.join(', ')}, but the request records no currency.`, codes)
    return field('UNCOMPARED', null, codes)
  }
  if (codes.every((code) => code === request.currency)) {
    signal(signals, 'currency.match', 'currency', 'MATCH', 'ok', `The text uses ${request.currency}, the request's currency.`, codes)
  } else if (codes.includes(request.currency)) {
    signal(signals, 'currency.mixed', 'currency', 'CONFLICT', 'warn', `The text mixes ${codes.join(' and ')}; the request is in ${request.currency}.`, codes)
  } else {
    signal(signals, 'currency.mismatch', 'currency', 'CONFLICT', 'bad', `The text uses ${codes.join(', ')}, but the request is in ${request.currency}.`, codes)
  }
  return field(statusOf(signals, 'currency'), request.currency, codes)
}

function comparePayee(extracted, request, profile, signals) {
  // One entry per distinct name (a label and a sentence often repeat it).
  const names = []
  for (const payee of extracted.payees) if (!names.some((name) => recipientSimilarity(name, payee.value) === 1)) names.push(payee.value)
  if (!names.length) return notPresent(request.recipient)
  if (!request.recipient) {
    signal(signals, 'payee.uncompared', 'payee', 'UNCOMPARED', null, `The text names ${list(names)} as the payee, but the request has no payee to compare with.`, names)
    return field('UNCOMPARED', null, names)
  }

  const knownPayee = (name) => (profile?.knownRecipients ?? []).find((recipient) => recipientSimilarity(recipient.name, name) === 1)
  const compared = names.map((name) => ({ name, similarity: Math.round(recipientSimilarity(name, request.recipient) * 1000) / 1000 }))
  const matches = compared.filter((entry) => entry.similarity === 1)
  const lookalikes = compared.filter((entry) => entry.similarity < 1 && entry.similarity >= LOOKALIKE_THRESHOLD)
  const others = compared.filter((entry) => entry.similarity < LOOKALIKE_THRESHOLD)

  if (matches.length) {
    signal(
      signals,
      'payee.match',
      'payee',
      'MATCH',
      'ok',
      `The text names ${quote(matches[0].name)}, the request's payee. A matching name does not prove who holds the account.`,
      matches,
    )
  }
  for (const entry of lookalikes) {
    signal(
      signals,
      'payee.lookalike',
      'payee',
      'CONFLICT',
      'warn',
      `The text names ${quote(entry.name)}, similar to but not the same as the request's payee ${quote(request.recipient)}.`,
      [entry],
    )
  }
  for (const entry of others) {
    const known = knownPayee(entry.name)
    // A single, different name with no matching one is a clear conflict.
    const clear = !matches.length && !lookalikes.length && others.length === 1
    signal(
      signals,
      'payee.mismatch',
      'payee',
      'CONFLICT',
      clear ? 'bad' : 'warn',
      `The text names ${quote(entry.name)}${known ? ' (an existing payee on this account)' : ''}, but the request pays ${quote(request.recipient)}.`,
      [entry],
    )
  }
  return field(statusOf(signals, 'payee'), request.recipient, compared)
}

// The request records where the payee banks relative to the customer
// (SAME_BANK / OTHER_LOCAL_BANK / OVERSEAS_BANK), not a bank name, so a bank
// named in the text can only be compared when the customer's bank is known.
// Banks named inside a sender claim ("MCB fraud department") describe the
// sender, not the payee, and are left out.
function compareBank(extracted, request, userBank, signals) {
  const inClaim = (bank) => extracted.senderClaims.some((claim) => bank.start >= claim.start && bank.end <= claim.end)
  const codes = unique(extracted.banks.filter((bank) => !inClaim(bank)).map((bank) => bank.code))
  const recipientBank = request.recipientBank == null ? null : normalizeRecipientBank(request.recipientBank)
  if (!codes.length) return notPresent(recipientBank)

  const expectation = (code) => {
    if (recipientBank === 'OVERSEAS_BANK') return 'CONFLICT'
    if (!userBank || !getBank(userBank)) return null
    if (recipientBank === 'SAME_BANK') return code === userBank ? 'MATCH' : 'CONFLICT'
    if (recipientBank === 'OTHER_LOCAL_BANK') return code !== userBank ? 'MATCH' : 'CONFLICT'
    return null
  }
  const destination = {
    SAME_BANK: `the customer's own bank${userBank ? ` (${bankName(userBank)})` : ''}`,
    OTHER_LOCAL_BANK: `another local bank${userBank ? ` (not ${bankName(userBank)})` : ''}`,
    OVERSEAS_BANK: 'an overseas bank',
  }

  const compared = codes.map((code) => ({ code, result: expectation(code) }))
  for (const { code, result } of compared) {
    if (result === 'MATCH') {
      signal(signals, 'bank.match', 'bank', 'MATCH', 'ok', `The text names ${bankName(code)}, consistent with the request paying ${destination[recipientBank]}.`, [code])
    } else if (result === 'CONFLICT') {
      // A bank named in free text may not be the payee's bank, so a conflict
      // is a warning, not proof.
      signal(signals, 'bank.mismatch', 'bank', 'CONFLICT', 'warn', `The text names ${bankName(code)}, but the request pays ${destination[recipientBank]}.`, [code])
    } else {
      signal(
        signals,
        'bank.uncompared',
        'bank',
        'UNCOMPARED',
        null,
        `The text names ${bankName(code)}; the request does not record enough about the payee's bank to compare.`,
        [code],
      )
    }
  }
  return field(statusOf(signals, 'bank'), recipientBank, codes, userBank ? { userBank } : {})
}

// The request may hold a full account number or, as in the demo requests,
// only its last four digits. Nothing beyond what it holds is compared.
function compareAccount(extracted, request, signals) {
  const full = extracted.accountNumbers.filter((account) => account.kind === 'ACCOUNT')
  const ibans = extracted.accountNumbers.filter((account) => account.kind === 'IBAN')
  const lastFour = extracted.accountLastFour
  const evidence = [
    ...full.map((account) => ({ kind: 'ACCOUNT', value: account.value, lastFour: account.lastFour })),
    ...ibans.map((account) => ({ kind: 'IBAN', value: account.value })),
    ...lastFour.map((account) => ({ kind: 'LAST_FOUR', value: account.value, lastFour: account.value })),
  ]
  const requestDigits = digitsOf(request.recipientAccount)
  if (!evidence.length) return notPresent(requestDigits || null)
  if (!requestDigits) {
    signal(signals, 'account.uncompared', 'account', 'UNCOMPARED', null, 'The text gives account details, but the request records no payee account to compare with.', evidence)
    return field('UNCOMPARED', null, evidence)
  }

  const requestLastFour = requestDigits.slice(-4)
  const requestIsFull = requestDigits.length > 4
  const results = evidence.map((item) => {
    if (item.kind === 'IBAN') {
      if (requestIsFull && requestDigits.length >= 6) return { ...item, result: item.value.includes(requestDigits) ? 'MATCH' : 'CONFLICT', basis: 'FULL' }
      return { ...item, result: 'UNCOMPARED', basis: null }
    }
    if (item.kind === 'ACCOUNT' && requestIsFull) return { ...item, result: item.value === requestDigits ? 'MATCH' : 'CONFLICT', basis: 'FULL' }
    return { ...item, result: item.lastFour === requestLastFour ? 'MATCH' : 'CONFLICT', basis: 'LAST_FOUR' }
  })

  const matches = results.filter((item) => item.result === 'MATCH')
  const conflicts = results.filter((item) => item.result === 'CONFLICT')
  if (matches.length) {
    const byLastFour = matches.every((item) => item.basis === 'LAST_FOUR')
    signal(
      signals,
      'account.match',
      'account',
      'MATCH',
      'ok',
      byLastFour
        ? `The account in the text ends ${requestLastFour}, like the request's payee account. Only the last four digits can be compared.`
        : `The account number in the text is the request's payee account.`,
      matches,
    )
  }
  if (conflicts.length) {
    const stated = unique(conflicts.map((item) => (item.basis === 'FULL' ? item.value : `ending ${item.lastFour}`)))
    signal(
      signals,
      'account.mismatch',
      'account',
      'CONFLICT',
      matches.length ? 'warn' : 'bad',
      `The text gives account ${stated.join(', ')}, but the request pays the account ending ${requestLastFour}.`,
      conflicts,
    )
  }
  for (const item of results.filter((entry) => entry.result === 'UNCOMPARED')) {
    signal(signals, 'account.uncompared', 'account', 'UNCOMPARED', null, 'The text gives an IBAN, which cannot be compared with the last four digits the request records.', [item])
  }
  return field(statusOf(signals, 'account'), requestDigits, results)
}

function compareReference(extracted, request, signals) {
  const references = unique(extracted.references.map((reference) => reference.value))
  const requestReference = request.reference ?? null
  if (!references.length) return notPresent(requestReference)
  if (!requestReference || INTERNAL_REFERENCE.test(requestReference)) {
    signal(
      signals,
      'reference.uncompared',
      'reference',
      'UNCOMPARED',
      null,
      requestReference
        ? `The text quotes ${list(references)}; the request's reference ${requestReference} is fraud.auth's own, so they cannot be compared.`
        : `The text quotes ${list(references)}, but the request has no reference to compare with.`,
      references,
    )
    return field('UNCOMPARED', requestReference, references)
  }

  const wanted = normalizeReference(requestReference)
  const matching = references.filter((reference) => normalizeReference(reference) === wanted)
  if (matching.length) {
    signal(signals, 'reference.match', 'reference', 'MATCH', 'ok', `The text quotes reference ${quote(matching[0])}, the same as the request.`, matching)
  } else {
    signal(
      signals,
      'reference.mismatch',
      'reference',
      'CONFLICT',
      references.length === 1 ? 'bad' : 'warn',
      `The text quotes ${list(references)}, but the request's reference is ${quote(requestReference)}.`,
      references,
    )
  }
  return field(statusOf(signals, 'reference'), requestReference, references)
}

// Whether `date` is a payment date of a schedule starting on `first`.
function onSchedule(date, first, frequency) {
  const days = dayNumber(date) - dayNumber(first)
  if (days === 0) return true
  if (days < 0) return false
  if (frequency === 'DAILY') return true
  if (frequency === 'WEEKLY') return days % 7 === 0
  if (frequency === 'MONTHLY') return date.day === first.day
  return false
}

// Dates in the text are compared with the request's first payment date.
// Dates without a year are only matched on day and month; they never produce
// a conflict, because which year they mean is unknown.
function compareDates(extracted, request, timeZone, signals) {
  const dates = extracted.dates
  if (!dates.length) return notPresent(request.date ?? null)
  const evidence = dates.map(({ text, value, day, month, year }) => ({ text, value, day, month, year }))
  if (!request.date) {
    signal(signals, 'date.uncompared', 'date', 'UNCOMPARED', null, 'The text gives a date, but the request has no payment date to compare with.', evidence)
    return field('UNCOMPARED', null, evidence)
  }

  const first = zonedParts(request.date, timeZone)
  const firstIso = isoDay(first)
  const frequency = request.frequency ?? 'ONE_OFF'
  const results = evidence.map((date) => {
    if (date.year == null) {
      const sameDay = date.day === first.day && (frequency === 'MONTHLY' || date.month === first.month)
      return { ...date, result: sameDay ? 'MATCH' : 'UNCOMPARED' }
    }
    if (onSchedule(date, first, frequency)) return { ...date, result: 'MATCH' }
    return { ...date, result: 'CONFLICT', relation: dayNumber(date) < dayNumber(first) ? 'BEFORE' : 'AFTER' }
  })

  const matches = results.filter((date) => date.result === 'MATCH')
  if (matches.length) {
    signal(signals, 'date.match', 'date', 'MATCH', 'ok', `The text's date ${quote(matches[0].text)} fits the request's payment schedule (first payment ${firstIso}).`, matches)
  }
  for (const date of results.filter((entry) => entry.result === 'CONFLICT')) {
    // A date in free text may be unrelated to the payment (an agreement date,
    // say), so these are warnings.
    const text =
      date.relation === 'BEFORE'
        ? `The text gives ${quote(date.text)} (${date.value}), before the request's first payment on ${firstIso}.`
        : `The text gives ${quote(date.text)} (${date.value}), after the first payment on ${firstIso} and not on the request's schedule.`
    signal(signals, `date.${date.relation.toLowerCase()}`, 'date', 'CONFLICT', 'warn', text, [date])
  }
  for (const date of results.filter((entry) => entry.result === 'UNCOMPARED')) {
    signal(signals, 'date.uncompared', 'date', 'UNCOMPARED', null, `The text gives ${quote(date.text)} without a year, so it cannot be placed against the request.`, [date])
  }
  return field(statusOf(signals, 'date'), firstIso, results)
}

function reviewSenderClaims(extracted, userBank, signals) {
  const claims = []
  for (const claim of extracted.senderClaims) if (!claims.some((seen) => seen.text.toLowerCase() === claim.text.toLowerCase())) claims.push(claim)
  if (!claims.length) return notPresent(null)
  const verbs = { DEPARTMENT: 'presents itself as', FROM: 'says it is', ON_BEHALF_OF: 'says it acts' }
  for (const claim of claims) {
    const otherBank = claim.bank && userBank && claim.bank !== userBank ? ` ${bankName(claim.bank)} is not the customer's bank.` : ''
    signal(
      signals,
      'sender.claim',
      'senderClaims',
      'SUSPICIOUS',
      'warn',
      `The text ${verbs[claim.kind] ?? 'claims to be'} ${quote(claim.text)}.${otherBank} The claim cannot be verified from the text itself.`,
      [{ text: claim.text, kind: claim.kind, value: claim.value, bank: claim.bank }],
    )
  }
  return field('SUSPICIOUS', null, claims.map(({ text, kind, bank }) => ({ text, kind, bank })))
}

// fraud.auth holds no list of the banks' official domains, so no domain is
// confirmed as genuine. A domain is flagged only for what it visibly does:
// using a bank's name, or security wording, or both. Any other domain is
// reported as present, not as suspicious; a domain is never flagged just for
// not ending in .mu.
function reviewLinks(extracted, signals) {
  const domains = unique(extracted.domains.map((domain) => domain.value))
  if (!domains.length) return notPresent(null)
  const reviewed = domains.map((domain) => {
    const labels = domain.replace(/^www\./, '').split('.').slice(0, -1).flatMap((label) => label.split('-'))
    const bank = labels.map((label) => BANK_DOMAIN_TOKENS.get(label)).find(Boolean) ?? null
    const securityWords = labels.filter((label) => SECURITY_DOMAIN_WORDS.has(label))
    return { domain, bank, securityWords }
  })

  for (const { domain, bank, securityWords } of reviewed) {
    const evidence = [{ domain, bank, securityWords }]
    if (bank && securityWords.length) {
      signal(
        signals,
        'link.lookalike',
        'links',
        'SUSPICIOUS',
        'bad',
        `The link ${domain} combines ${bankName(bank)}'s name with ${list(securityWords)}, a common pattern for look-alike bank sites.`,
        evidence,
      )
    } else if (bank) {
      signal(signals, 'link.bankName', 'links', 'SUSPICIOUS', 'warn', `The link ${domain} uses ${bankName(bank)}'s name; fraud.auth cannot confirm it belongs to the bank.`, evidence)
    } else if (securityWords.length) {
      signal(signals, 'link.securityWording', 'links', 'SUSPICIOUS', 'warn', `The link ${domain} uses security wording (${list(securityWords)}).`, evidence)
    } else {
      signal(signals, 'link.present', 'links', 'UNCOMPARED', null, `The text links to ${domain}.`, evidence)
    }
  }
  return field(statusOf(signals, 'links'), null, reviewed)
}

function reviewSensitiveRequests(text, signals) {
  if (text == null) return field('NOT_CHECKED', null, [])
  const mentions = unique([...text.matchAll(SENSITIVE_INFO)].map((match) => match[0].toLowerCase()))
  if (!mentions.length) return notPresent(null)
  signal(
    signals,
    'sensitive.request',
    'sensitiveInfo',
    'SUSPICIOUS',
    'bad',
    `The text mentions ${list(mentions)}. Banks do not ask for these in a message.`,
    mentions,
  )
  return field('SUSPICIOUS', null, mentions)
}

// Contradictions within the text itself, as far as the extractor can show
// them. (Amounts written in words are not extracted, so words-versus-digits
// is not checked.)
function reviewConsistency(extracted, signals) {
  const amounts = unique(extracted.amounts.map((amount) => money(amount.value, amount.currency)))
  if (amounts.length > 1) {
    signal(signals, 'consistency.amounts', 'consistency', 'SUSPICIOUS', 'warn', `The text mentions ${amounts.length} different amounts: ${amounts.join(', ')}.`, amounts)
  }
  const currencies = unique(extracted.currencies.map((currency) => currency.code))
  if (currencies.length > 1) {
    signal(signals, 'consistency.currencies', 'consistency', 'SUSPICIOUS', 'warn', `The text mixes currencies: ${currencies.join(', ')}.`, currencies)
  }
  const accountEndings = unique([
    ...extracted.accountNumbers.filter((account) => account.kind === 'ACCOUNT').map((account) => account.lastFour),
    ...extracted.accountLastFour.map((account) => account.value),
  ])
  if (accountEndings.length > 1) {
    signal(
      signals,
      'consistency.accounts',
      'consistency',
      'SUSPICIOUS',
      'warn',
      `The text refers to ${accountEndings.length} different accounts (ending ${accountEndings.join(', ')}).`,
      accountEndings,
    )
  }
  const payees = []
  for (const payee of extracted.payees) if (!payees.some((name) => recipientSimilarity(name, payee.value) === 1)) payees.push(payee.value)
  if (payees.length > 1) {
    signal(signals, 'consistency.payees', 'consistency', 'SUSPICIOUS', 'warn', `The text names ${payees.length} different payees: ${list(payees)}.`, payees)
  }
  return field(signals.some((s) => s.field === 'consistency') ? 'SUSPICIOUS' : 'NOT_PRESENT', null, [])
}

// --- Entry points -----------------------------------------------------------

// Compares entities extracted by extractEntities (extract.js) with a pending
// request and the user's profile. Options:
//   text     — the original text, needed for checks that read wording rather
//              than entities (requests for a PIN or OTP). Without it those
//              checks report NOT_CHECKED.
//   userBank — the customer's bank code (MCB / SBM / MAUBANK). The request
//              stores the payee's bank relative to it, so without it a named
//              bank can only be compared against an overseas request.
export function compareEvidence(extracted, request, profile, { text = null, userBank = null } = {}) {
  const entities = { ...extractEntities(''), ...extracted }
  const pending = request ?? {}
  const timeZone = profile?.timezone ?? APP_TIMEZONE
  const signals = []

  const fields = {
    amount: compareAmount(entities, pending, signals),
    currency: compareCurrency(entities, pending, signals),
    payee: comparePayee(entities, pending, profile, signals),
    bank: compareBank(entities, pending, userBank, signals),
    account: compareAccount(entities, pending, signals),
    reference: compareReference(entities, pending, signals),
    date: compareDates(entities, pending, timeZone, signals),
    senderClaims: reviewSenderClaims(entities, userBank, signals),
    links: reviewLinks(entities, signals),
    sensitiveInfo: reviewSensitiveRequests(text, signals),
    consistency: reviewConsistency(entities, signals),
  }

  const count = (category) => signals.filter((s) => s.category === category).length
  const summary = {
    matches: count('MATCH'),
    conflicts: count('CONFLICT'),
    suspicious: count('SUSPICIOUS'),
    uncompared: count('UNCOMPARED'),
    notPresent: Object.values(fields).filter((entry) => entry.status === 'NOT_PRESENT').length,
  }
  // A description of the evidence, not a verdict.
  const status = summary.conflicts
    ? 'CONFLICTING'
    : summary.suspicious
      ? 'SUSPICIOUS'
      : summary.matches
        ? 'CONSISTENT'
        : summary.uncompared
          ? 'UNVERIFIED'
          : 'NO_EVIDENCE'

  return {
    status,
    summary,
    fields,
    signals,
    findings: signals.filter((s) => s.tone).map(({ tone, text: findingText }) => ({ tone, text: findingText })),
  }
}

// Extracts entities from `text` and compares them in one step.
export function compareTextEvidence(text, request, profile, options = {}) {
  return compareEvidence(extractEntities(text), request, profile, { ...options, text: text ?? '' })
}
